### ISSUE TITLE
Honor not saving image in DCIM

### ISSUE THREAD

**Issue by snajdovski** [robertlevonyan/camerax-demo#15]
Great Demo but there is a minor issue with saving files, even if all permissions are added the app wont save the capture.
Here is debug log:
```
E/CameraXDemo: Photo capture failed: Failed to write temp file
W/System.err: androidx.camera.core.ImageCaptureException: Failed to write temp file
        at androidx.camera.core.ImageCapture$2.onError(ImageCapture.java:919)
W/System.err:     at androidx.camera.core.ImageSaver.lambda$postError$2$ImageSaver(ImageSaver.java:319)
        at androidx.camera.core.-$$Lambda$ImageSaver$q5J8WAquxyekKA6et-sNzW3OiJM.run(Unknown Source:8)
        at android.os.Handler.handleCallback(Handler.java:907)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
    Caused by: java.io.FileNotFoundException: /storage/emulated/0/DCIM/CameraXDemo/CameraXec1baf11-03e1-4da7-be06-0194bc9e3f32.tmp (No such file or directory)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:308)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:238)
W/System.err:     at java.io.FileOutputStream.<init>(FileOutputStream.java:180)
        at androidx.camera.core.ImageSaver.saveImageToTempFile(ImageSaver.java:118)
        at androidx.camera.core.ImageSaver.run(ImageSaver.java:85)
        at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err:     at java.lang.Thread.run(Thread.java:784)
D/OpenGLRenderer:   HWUI Binary is  enabled
D/OpenGLRenderer:   HWUI Binary is  enabled
I/GRALLOC: LockFlexLayout: baseFormat: 11, yStride: 1280, ySize: 921600, uOffset: 921600,  uStride: 1280
D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
```

**Comment by robertlevonyan** [comment]
What is the android version on your device?

**Comment by snajdovski** [comment]
> 
> 
> What is the android version on your device?

Android 9 Pie

**Comment by snajdovski** [comment]
I think it needs manifest permission

**Comment by robertlevonyan** [comment]
I've fixed it. The issue was in the path on devices lower than Android Q. Thank you for reporting.
